# playbooks/add_machine.yaml
- name: Create MAAS machine and configure MAC, IP, zone, and pool
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../vars/auth_vars.yaml
    - ../vars/add_machine_vars.yaml

  pre_tasks:
    - name: 检查变量是否定义
      fail:
        msg: >
          必须提供 'hostname', 'mac_address', and 'ip_address'，请使用-e指定或者在其他变量文件中指定
      when: hostname is not defined or mac_address is not defined or ip_address is not defined

  tasks:
    - name: 查询是否存在同名主机
      uri:
        url: "{{ maas_url }}api/2.0/machines/?hostname={{ hostname }}"
        method: GET
        headers:
          Authorization: "{{ oauth_header }}"
        return_content: yes
      register: existing_host_resp

    - name: 设置变量：host_exists
      set_fact:
        host_exists: "{{ existing_host_resp.json | length > 0 }}"

    - name: 添加主机
      uri:
        url: "{{ maas_url }}api/2.0/machines/"
        method: POST
        body_format: form-urlencoded
        body:
          architecture: "amd64"
          power_type: "{{ power_type }}"
          power_parameters: "{{ power_parameters }}"
          hostname: "{{ hostname }}"
          mac_addresses: "{{ mac_address }}"
        status_code: 200
        return_content: yes
        headers:
          Authorization: "{{ oauth_header }}"
      register: machine_created
      when: not host_exists

    - name: 获取主机的system_id
      set_fact:
        system_id: "{{ machine_created.json.system_id }}"
      when: not host_exists

    - name: 设置zone和pool
      uri:
        url: "{{ maas_url }}api/2.0/machines/{{ system_id }}/"
        method: PUT
        body_format: form-urlencoded
        body:
          zone: "{{ zone }}"
          pool: "{{ pool }}"
        status_code: 200
        headers:
          Authorization: "{{ oauth_header }}"
      when: not host_exists
