- name: Change machine status in MAAS
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/auth_vars.yaml
  vars:
    action_map:
      locked: op-lock
      unlocked: op-unlock
      broken: op-mark_broken
      fixed: op-mark_fixed
      released: op-release
      commissioning: op-commission
      rescue_mode: op-rescue_mode
      exit_rescue: op-exit_rescue_mode
      power_on: op-power_on
      power_off: op-power_off
  pre_tasks:
    - name: 检查必传参数 hostname
      fail:
        msg: "参数 hostname 必须传入"
      when: hostname is not defined or hostname == ""

    - name: 检查必传参数 target_state
      fail:
        msg: "参数 os 必须传入"
      when: target_state is not defined or target_state == ""

  tasks:
    - name: 获取主机信息
      uri:
        url: "{{ maas_url }}api/2.0/machines/?hostname={{ hostname }}"
        method: GET
        headers:
          Authorization: "{{ oauth_header }}"
        return_content: yes
      register: machine_info_resp


    - name: 检查主机是否存在
      fail:
        msg: "主机 {{ hostname }} 在 MAAS 中未找到"
      when: machine_info_resp.json | length == 0

    - name: 选择对应的动作API
      set_fact:
        action_api: "{{ action_map[target_state] | default('') }}"

    - name: 校验是否支持该状态变更
      fail:
        msg: "目标状态 {{ target_state }} 不支持"
      when: action_api == ''

    - name: 更改机器状态
      uri:
        url: "{{ maas_url }}/api/2.0/machines/{{ machine_info_resp.json[0].system_id }}/{{ action_api }}"
        method: POST
        body_format: form-urlencoded
        body: ""
        status_code: 200
        return_content: yes
        headers:
          Authorization: "{{ oauth_header }}"
