# playbooks/deploy_os.yaml
- name: Deploy OS via MAAS
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/auth_vars.yaml

  vars:
    # 默认值，除必传项外
    enable_hw_sync: false
    install_kvm: false
    install_rackd: false
    register_vmhost: false
    user_data: ""

  pre_tasks:
    - name: 检查必传参数 hostname
      fail:
        msg: "参数 hostname 必须传入"
      when: hostname is not defined or hostname == ""

    - name: 检查必传参数 os
      fail:
        msg: "参数 os 必须传入"
      when: os is not defined or os == ""
    - name: 如果传入 user_data 文件路径，读取并 Base64 编码
      when: user_data != ""
      set_fact:
        user_data: "{{ lookup('file', user_data) | b64encode }}"

  tasks:
    - name: 获取主机信息
      uri:
        url: "{{ maas_url }}api/2.0/machines/?hostname={{ hostname }}"
        method: GET
        headers:
          Authorization: "{{ oauth_header }}"
        return_content: yes
      register: machine_info_resp

    - name: 提取主机信息
      set_fact:
        machine_info: "{{ machine_info_resp.json[0] }}"
      when: machine_info_resp.json | length > 0

    - name: 检查主机是否存在
      fail:
        msg: "主机 {{ hostname }} 在 MAAS 中未找到"
      when: machine_info_resp.json | length == 0

    - name: 校验主机状态是否允许部署
      fail:
        msg: "主机 {{ hostname }} 当前状态为 {{ machine_info.status_name }}，不允许部署（仅允许 Ready 或 Released）"
      when: machine_info.status_name not in ['Ready', 'Released']

    - name: "{{ hostname }} 部署操作系统"
      uri:
        url: "{{ maas_url }}api/2.0/machines/{{ machine_info.system_id }}/op-deploy"
        method: POST
        headers:
          Authorization: "{{ oauth_header }}"
        body_format:  form-urlencoded
        body:
          distro_series: "{{ os }}"
          enable_hw_sync: "{{ enable_hw_sync }}"
          install_kvm: "{{ install_kvm }}"
          install_rackd: "{{ install_rackd }}"
          register_vmhost: "{{ register_vmhost }}"
          user_data: "{{ user_data }}"
      register: deploy_resp
      failed_when: false

    - name: 输出部署结果
      debug:
        msg: >-
          {% if deploy_resp.status == 200 %}
          部署成功，状态码 {{ deploy_resp.status }}
          {% else %}
          部署失败，状态码 {{ deploy_resp.status }}，错误信息：{{ deploy_resp.json }}
          {% endif %}

          
